CC		=	gcc
CFLAGS	=	-I. -g -lcrypt

TARGET	=	zftp
OBJS	=	main.o hash.o utils.o tunables.o parseconf.o str.o prelogin.o connrec.o ftpcode.o\
			ftpcmdio.o privsock.o process.o zsignal.o privops.o

DEPS	=	hash.h utils.h tunables.h session.h connrec.h parseconf.h str.h ftpcode.h err.h\
			prelogin.h privops.h

TPO		= 	testparseconf.o parseconf.o str.o tunables.o utils.o
THO		= 	testhash.o hash.o

all : $(TARGET)
.PHONY : all

.c.o:
	$(CC) -c $(CFLAGS) -o $@ $<

$(TARGET): $(OBJS) $(DEPS)
	$(CC) -o $(TARGET) $(OBJS) $(CFLAGS)

*.o: Makefile

testhash: hash.h $(THO)
	$(CC) -o testhash $(THO)

testparseconf: parseconf.h tunables.h $(TPO)
	$(CC) -o testparseconf $(TPO)


.PHONY : clean cleanall
clean:
	-rm -f *.o $(TARGET)

cleanall:
	-rm -f *.o $(TARGET) testhash testparseconf